# My first workflow :
name: My first github action

on:
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Print Hello
        run: echo "Hello Git, My github action is working "
